Repository goottflix/be-goottflix, pull requests merged in 2024-09, with the labels that each got.

#10 [Feat,Git] Spring security를 이용한 회원가입,로그인,소셜로그인 완성 / env 파일을 통해 민감한정보 감추기
  build.gradle
  src/main/java/com/goottflix/config/CorsMvcConfig.java
  src/main/java/com/goottflix/config/SecurityConfig.java
  src/main/java/com/goottflix/user/controller/JoinController.java
  src/main/java/com/goottflix/user/controller/LoginController.java
  src/main/java/com/goottflix/user/controller/TestController.java
  src/main/java/com/goottflix/user/jwt/JWTFilter.java
  src/main/java/com/goottflix/user/jwt/JWTUtil.java
  src/main/java/com/goottflix/user/jwt/LoginFilter.java
  src/main/java/com/goottflix/user/model/CustomUserDetails.java
  src/main/java/com/goottflix/user/model/JoinDTO.java
  src/main/java/com/goottflix/user/model/LoginDTO.java
  src/main/java/com/goottflix/user/model/User.java
  src/main/java/com/goottflix/user/model/UserDTO.java
  src/main/java/com/goottflix/user/model/repository/UserMapper.java
  src/main/java/com/goottflix/user/service/CustomOAuth2UserService.java
  src/main/java/com/goottflix/user/service/CustomUserDetailsService.java
  src/main/java/com/goottflix/user/service/JoinService.java
  src/main/java/com/goottflix/user/service/LoginService.java
  src/main/java/com/goottflix/user/social/CustomSuccessHandler.java
  src/main/java/com/goottflix/user/social/dto/CustomOAuth2User.java
  src/main/java/com/goottflix/user/social/dto/GoogleResponse.java
  src/main/java/com/goottflix/user/social/dto/NaverResponse.java
  src/main/java/com/goottflix/user/social/dto/OAuth2Response.java
  src/main/resources/application.properties
  src/main/resources/config/mysql/create.sql
  src/main/resources/config/mysql/insert.sql
  src/main/resources/mappers/user/usermapper.xml
Labels: DOCS, Feature

#11 [Git]민감한정보 삭제
  src/main/resources/application.properties
Labels: DOCS

#15 [Feat,Fix] 카카오 로그인 추가,로그아웃 추가(만료토큰 발행), moviemapper 테이블명일치
  src/main/java/com/goottflix/movie/controller/MovieApiController.java
  src/main/java/com/goottflix/user/controller/LoginController.java
  src/main/java/com/goottflix/user/controller/TestController.java
  src/main/java/com/goottflix/user/service/CustomOAuth2UserService.java
  src/main/java/com/goottflix/user/social/CustomSuccessHandler.java
  src/main/java/com/goottflix/user/social/dto/KakaoResponse.java
  src/main/resources/application.properties
  src/main/resources/config/mysql/insert.sql
Labels: Feature, Fix

#13 [Feat,Fix] movie mapper변경, 친구리스트,추가할 친구목록 가져오기
  src/main/java/com/goottflix/config/SecurityConfig.java
  src/main/java/com/goottflix/friend/controller/FriendController.java
  src/main/java/com/goottflix/friend/entity/FriendNotifyDTO.java
  src/main/java/com/goottflix/friend/entity/repository/FriendMapper.java
  src/main/java/com/goottflix/friend/service/FriendService.java
  src/main/java/com/goottflix/notify/controller/NotifyController.java
  src/main/java/com/goottflix/notify/entity/repository/NotifyMapper.java
  src/main/java/com/goottflix/notify/service/NotifyService.java
  src/main/resources/config/mysql/create.sql
  src/main/resources/config/mysql/insert.sql
  src/main/resources/mappers/friend/FriendMapper.xml
  src/main/resources/mappers/notify/NotifyMapper.xml
Labels: Feature, Fix

#18 [Feat] 관리자페이지 - 새로운영화추가,영화목록보고 알림보내기 기능
  src/main/java/com/goottflix/movie/controller/MovieApiController.java
  src/main/java/com/goottflix/movie/service/MovieService.java
  src/main/java/com/goottflix/notify/controller/NotifyController.java
  src/main/java/com/goottflix/notify/service/NotifyService.java
  src/main/java/com/goottflix/subscribe/service/SubscribeService.java
  src/main/java/com/goottflix/user/model/repository/UserMapper.java
  src/main/resources/mappers/movie/MovieMapper.xml
  src/main/resources/mappers/user/usermapper.xml
  src/main/resources/templates/movieWrite.html
Labels: Feature

#20 [Feat] 아두이노 - 연결,cards테이블 변경, insert,update,예매정보 출력
  build.gradle
  src/main/java/com/goottflix/book/SerialPortReader.java
  src/main/java/com/goottflix/book/controller/BookController.java
  src/main/java/com/goottflix/book/model/BookInfo.java
  src/main/java/com/goottflix/book/model/Cards.java
  src/main/java/com/goottflix/book/model/NfcRequest.java
  src/main/java/com/goottflix/book/model/repository/CardMapper.java
  src/main/java/com/goottflix/book/service/CardService.java
  src/main/java/com/goottflix/config/SecurityConfig.java
  src/main/java/com/goottflix/config/SerialPortConfig.java
  src/main/resources/config/mysql/create.sql
  src/main/resources/mappers/cards/cardsmapper.xml
  src/main/resources/templates/nfc-data.html
Labels: Feature
